#if !defined(__CPP_ABSTRACT_DATA_BASE_FILE_SYSTEM_STRUCTURE_FORWARD_DECLARATION_HPP__)
# define __CPP_ABSTRACT_DATA_BASE_FILE_SYSTEM_STRUCTURE_FORWARD_DECLARATION_HPP__

namespace CppAbstractDataBase {
  struct FileSystemStructure;
} /// end namespace CppAbstractDataBase

#endif /// !__CPP_ABSTRACT_DATA_BASE_FILE_SYSTEM_STRUCTURE_FORWARD_DECLARATION_HPP__
