#if !defined(__CPP_ABSTRACT_DATA_BASE_VERSION_HPP__)
# define __CPP_ABSTRACT_DATA_BASE_VERSION_HPP__

///  CPP_ABSTRACT_DATA_BASE_VERSION % 100 is the patch level
///  CPP_ABSTRACT_DATA_BASE_VERSION / 100 % 1000 is the minor version
///  CPP_ABSTRACT_DATA_BASE_VERSION / 100000 is the major version

#define CPP_ABSTRACT_DATA_BASE_VERSION 100000

#endif /// !__CPP_ABSTRACT_DATA_BASE_VERSION_HPP__
